In [1]:
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.randint(3, size = 3)

array([2, 1, 0])

In [18]:
A = np.array([[0, 9, 19, 13],
              [1, 20, 5, 13],
             [12, 11, 3, 4]])
B = np.array([[2, 0, 0, 0],
             [1, 2, 2, 0],
             [2, 1, 1, 0],
             [0, 0, 1, 1]])

A.dot(B)

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [22]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
b

array([[-1, 33,  4,  1],
       [ 0,  1,  1,  0]])

In [23]:
b.mean()

4.875

In [44]:
F = np.array([[1, -1, -1, 0],
             [-1, 2, -1, -1],
             [-1, -1, 2, -1],
             [0, -1, -1, 1]])

F

array([[ 1, -1, -1,  0],
       [-1,  2, -1, -1],
       [-1, -1,  2, -1],
       [ 0, -1, -1,  1]])

In [47]:
np.linalg.eig(F)[0]

array([-1.,  1.,  3.,  3.])

In [39]:
np.linalg.eig(np.array([[0, 3],[3, 8]]))[0]

array([-1.,  9.])

In [24]:
K = np.array([[2, 4, 0, 4, 1],
             [2, 4, 1, 1, 0],
             [1, 1, 1, 2, 2],
             [0, 1, 3, 2, 4],
             [2, 2, 2, 0, 2]])
K

array([[2, 4, 0, 4, 1],
       [2, 4, 1, 1, 0],
       [1, 1, 1, 2, 2],
       [0, 1, 3, 2, 4],
       [2, 2, 2, 0, 2]])

In [31]:
Ko = np.linalg.inv(K)
Ko.diagonal().sum()

2.700000000000001

In [54]:
from numpy.linalg import matrix_rank

def LI_vecs(dim,M):
    LI=[M[0]]
    for i in range(dim):
        tmp=[]
        for r in LI:
            tmp.append(r)
        tmp.append(M[i])                #set tmp=LI+[M[i]]
        if matrix_rank(tmp)>len(LI):    #test if M[i] is linearly independent from all (row) vectors in LI
            LI.append(M[i])             #note that matrix_rank does not need to take in a square matrix
    return LI                           #return set of linearly independent (row) vectors

#Example
mat=np.array([[6, 0, 3],
             [0, -1, 2],
             [12, 3, 0]])
LI_vecs(3,mat)

[array([6, 0, 3]), array([ 0, -1,  2])]

In [55]:
mat

array([[ 6,  0,  3],
       [ 0, -1,  2],
       [12,  3,  0]])